# docker compose file for redis with port mapping

version: '3.7'

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-volume-data:/data


volumes:
  redis-volume-data:
